<a href="https://colab.research.google.com/github/Neilton-Cunha/Exercicios-Alura/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas

O CSV, que significa comma separated values (valores separados por vírgula), é um formato de arquivo onde os valores são separados por vírgulas.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/meu_csv.csv')
df

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

In [ ]:
df.head()

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8
4  Eduarda    5.9

In [ ]:
df.tail()

       nome  media
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

# Desafio

In [ ]:
import os
from google.colab import userdata

In [ ]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 525.8 kB/s eta 0:00:00

In [ ]:
os.environ['GROQ_API_KEY'] = userdata.get('Groq_API_Key')

In [ ]:
perguntas = [
    "O que é uma escala musical?",
    "Qual a diferença entre tom e semitom?",
    "O que forma um acorde maior?",
    "O que é um compasso na música?",
    "Qual a função da clave de sol?",
    "O que significa andamento em uma composição?",
    "O que é uma progressão harmônica?",
    "Qual a diferença entre melodia e harmonia?",
    "O que é um intervalo musical?",
    "Quais são as notas da escala de Dó Maior?"
]

In [ ]:
with open("Perguntas de musica.txt", "w" , encoding = 'utf-8') as desafio:
   for exercicio in perguntas:
      desafio.write (exercicio +'\n')

In [ ]:
nova_lista_de_perguntas = []

with open("Perguntas de musica.txt", "r" , encoding = 'utf-8') as desafio:
  for exercicio in desafio:
      nova_lista_de_perguntas.append(exercicio.strip())

In [ ]:
from groq import Groq

respostas = []

client_groq = Groq()
completion = client_groq.chat.completions.create(
      model="openai/gpt-oss-20b",
      messages=[
      {
        "role": "user",
        "content":f'responde de forma sucinta essas perguntas, mas so reotrne as respostas, sem enumera-las: {perguntas}'
      }
    ],
    temperature=1,
    max_completion_tokens=7000,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

resposta = ''

for chunk in completion:
    resposta += chunk.choices[0].delta.content or ""

respostas.append(resposta)

In [ ]:
respostas_separadas = []

for linha in respostas[0].split('\n'):
    if linha.strip():
        respostas_separadas.append(linha.strip())

In [ ]:
dicionario = {'Perguntas': nova_lista_de_perguntas, 'Respostas': respostas_separadas}
df = pd.DataFrame(dicionario)
df.to_csv("Perguntas de musica.csv", index=False, encoding="utf-8")

In [ ]:
df = pd.read_csv('/content/Perguntas de musica.csv')
df

,Perguntas,Respostas
0,O que é uma escala musical?,Uma escala musical é uma sequência ordenada de...
1,Qual a diferença entre tom e semitom?,"Um tom equivale a dois semitons, enquanto um s..."
2,O que forma um acorde maior?,Um acorde maior é formado por uma tríade que c...
3,O que é um compasso na música?,Um compasso é uma divisão de medida que agrupa...
4,Qual a função da clave de sol?,A clave de sol indica a posição das notas na p...
5,O que significa andamento em uma composição?,Andamento indica a velocidade ou tempo em que ...
6,O que é uma progressão harmônica?,Uma progressão harmônica é uma sequência de ac...
7,Qual a diferença entre melodia e harmonia?,"Melodia é a linha rítmica e tonal única, enqua..."
8,O que é um intervalo musical?,Um intervalo musical é a distância entre duas ...
9,Quais são as notas da escala de Dó Maior?,"As notas da escala de Dó Maior são: Dó, Ré, Mi..."