<a href="https://colab.research.google.com/github/Neilton-Cunha/Exercicios-Alura/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas

O CSV, que significa comma separated values (valores separados por vírgula), é um formato de arquivo onde os valores são separados por vírgulas.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/meu_csv.csv')
df

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

In [ ]:
df.head()

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8
4  Eduarda    5.9

In [ ]:
df.tail()

       nome  media
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

# Desafio

In [ ]:
import os
from google.colab import userdata

In [ ]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 3.5 MB/s eta 0:00:00

In [ ]:
os.environ['GROQ_API_KEY'] = userdata.get('Groq_API_Key')

In [ ]:
perguntas = [
    "O que é uma escala musical?",
    "Qual a diferença entre tom e semitom?",
    "O que forma um acorde maior?",
    "O que é um compasso na música?",
    "Qual a função da clave de sol?",
    "O que significa andamento em uma composição?",
    "O que é uma progressão harmônica?",
    "Qual a diferença entre melodia e harmonia?",
    "O que é um intervalo musical?",
    "Quais são as notas da escala de Dó Maior?"
]

In [ ]:
with open("Perguntas de musica.txt", "w" , encoding = 'utf-8') as desafio:
   for exercicio in perguntas:
      desafio.write (exercicio +'\n')

In [ ]:
nova_lista_de_perguntas = []

with open("Perguntas de musica.txt", "r" , encoding = 'utf-8') as desafio:
  for exercicio in desafio:
      nova_lista_de_perguntas.append(exercicio.strip())

In [ ]:
from groq import Groq

respostas = []

client_groq = Groq()
completion = client_groq.chat.completions.create(
      model="openai/gpt-oss-20b",
      messages=[
      {
        "role": "user",
        "content":f'responde de forma sucinta essas perguntas, mas so reotrne as respostas, sem enumera-las: {perguntas}'
      }
    ],
    temperature=1,
    max_completion_tokens=7000,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

resposta = ''

for chunk in completion:
    resposta += chunk.choices[0].delta.content or ""

respostas.append(resposta)

In [ ]:
respostas_separadas = []

for linha in respostas[0].split('\n'):
    if linha.strip():
        respostas_separadas.append(linha.strip())

In [ ]:
dicionario = {'Perguntas': nova_lista_de_perguntas, 'Respostas': respostas_separadas}
df = pd.DataFrame(dicionario)
df.to_csv("Perguntas de musica.csv", index=False, encoding="utf-8")

In [ ]:
df = pd.read_csv('/content/Perguntas de musica.csv')
df

,Perguntas,Respostas
0,O que é uma escala musical?,Uma escala musical é uma sequência ordenada de...
1,Qual a diferença entre tom e semitom?,"Um tom equivale a dois semitons, enquanto um s..."
2,O que forma um acorde maior?,Um acorde maior é formado por uma tríade que c...
3,O que é um compasso na música?,Um compasso é uma divisão de medida que agrupa...
4,Qual a função da clave de sol?,A clave de sol indica a posição das notas na p...
5,O que significa andamento em uma composição?,Andamento indica a velocidade ou tempo em que ...
6,O que é uma progressão harmônica?,Uma progressão harmônica é uma sequência de ac...
7,Qual a diferença entre melodia e harmonia?,"Melodia é a linha rítmica e tonal única, enqua..."
8,O que é um intervalo musical?,Um intervalo musical é a distância entre duas ...
9,Quais são as notas da escala de Dó Maior?,"As notas da escala de Dó Maior são: Dó, Ré, Mi..."

## Dataframe criado por IA

In [ ]:
import pandas as pd
import numpy as np

# Definindo os dados para as colunas
nomes_produtos = [f"Produto {i+1}" for i in range(50)]
categorias_produtos = np.random.choice(["Eletrônicos", "Livros", "Roupas", "Alimentos", "Brinquedos"], 50)
precos_produtos = np.random.uniform(10.0, 500.0, 50).round(2)
itens_vendidos = np.random.randint(1, 1000, 50)
avaliacoes_produtos = np.random.uniform(1.0, 5.0, 50).round(1)

# Criando o DataFrame
df_produtos = pd.DataFrame({
    "Nome do produto": nomes_produtos,
    "Categoria do produto": categorias_produtos,
    "Preço do produto": precos_produtos,
    "Itens vendidos": itens_vendidos,
    "Avaliação do produto": avaliacoes_produtos
})

# Exibindo as primeiras linhas do DataFrame
df_produtos.head()

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
0,Produto 1,Brinquedos,449.62,661,4.7
1,Produto 2,Eletrônicos,117.81,308,3.4
2,Produto 3,Alimentos,49.05,106,1.8
3,Produto 4,Eletrônicos,296.20,255,4.5
4,Produto 5,Alimentos,355.20,681,1.4

In [ ]:
df_produtos.head()["Categoria do produto"]

0     Alimentos
1     Alimentos
2    Brinquedos
3        Livros
4        Roupas
Name: Categoria do produto, dtype: object

In [ ]:
df_produtos["Categoria do produto"].unique()

array(['Alimentos', 'Brinquedos', 'Livros', 'Roupas', 'Eletrônicos'],
      dtype=object)

In [ ]:
set(df_produtos["Categoria do produto"])

{'Alimentos', 'Brinquedos', 'Eletrônicos', 'Livros', 'Roupas'}

# Filtro

In [ ]:

df_produtos[df_produtos["Categoria do produto"] == "Eletrônicos"]

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
1,Produto 2,Eletrônicos,117.81,308,3.4
3,Produto 4,Eletrônicos,296.20,255,4.5
8,Produto 9,Eletrônicos,197.16,261,4.8
11,Produto 12,Eletrônicos,427.87,450,5.0
15,Produto 16,Eletrônicos,205.30,234,3.0
23,Produto 24,Eletrônicos,204.36,373,2.5
34,Produto 35,Eletrônicos,388.80,629,1.3
37,Produto 38,Eletrônicos,246.31,793,4.8
39,Produto 40,Eletrônicos,271.57,265,3.4
44,Produto 45,Eletrônicos,370.17,270,1.1

In [ ]:
df_produtos[df_produtos["Avaliação do produto"] < 2.0]

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
2,Produto 3,Alimentos,49.05,106,1.8
4,Produto 5,Alimentos,355.20,681,1.4
9,Produto 10,Alimentos,466.88,411,1.5
20,Produto 21,Livros,177.06,68,1.9
32,Produto 33,Alimentos,406.45,788,1.9
34,Produto 35,Eletrônicos,388.80,629,1.3
40,Produto 41,Brinquedos,467.79,823,1.7
44,Produto 45,Eletrônicos,370.17,270,1.1
49,Produto 50,Roupas,450.12,699,1.5

In [ ]:
df_produtos.shape
#chama o tamanho do dataframe

(50, 5)

In [ ]:
df_produtos_filtro_avaliacao_menor_que_2 = df_produtos[df_produtos["Avaliação do produto"] < 2.0]
df_produtos_filtro_avaliacao_menor_que_2

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
2,Produto 3,Alimentos,49.05,106,1.8
4,Produto 5,Alimentos,355.20,681,1.4
9,Produto 10,Alimentos,466.88,411,1.5
20,Produto 21,Livros,177.06,68,1.9
32,Produto 33,Alimentos,406.45,788,1.9
34,Produto 35,Eletrônicos,388.80,629,1.3
40,Produto 41,Brinquedos,467.79,823,1.7
44,Produto 45,Eletrônicos,370.17,270,1.1
49,Produto 50,Roupas,450.12,699,1.5

In [ ]:
df_produtos_filtro_avaliacao_menor_que_2.shape

(9, 5)

In [ ]:
df_produtos[(df_produtos["Categoria do produto"] == "Eletrônicos") & (df_produtos["Preço do produto"] >= 350.0)]
#Para quando for chamar mais de um elemento do dataframe

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
11,Produto 12,Eletrônicos,427.87,450,5.0
34,Produto 35,Eletrônicos,388.80,629,1.3
44,Produto 45,Eletrônicos,370.17,270,1.1

In [ ]:
df_produtos.iloc[15]
# faz busca por indice

Nome do produto          Produto 16
Categoria do produto    Eletrônicos
Preço do produto              205.3
Itens vendidos                  234
Avaliação do produto            3.0
Name: 15, dtype: object

In [ ]:
df_produtos.iloc[0:2]
#pode ser usado pra buscar mais de um indice

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
0,Produto 1,Brinquedos,449.62,661,4.7
1,Produto 2,Eletrônicos,117.81,308,3.4

In [ ]:
df_produtos_com_indice = df_produtos.set_index("Nome do produto")
df_produtos_com_indice
# o nome do produto passa a ser indice

,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
Nome do produto,,,,
Produto 1,Brinquedos,449.62,661,4.7
Produto 2,Eletrônicos,117.81,308,3.4
Produto 3,Alimentos,49.05,106,1.8
Produto 4,Eletrônicos,296.20,255,4.5
Produto 5,Alimentos,355.20,681,1.4
Produto 6,Roupas,138.71,476,2.0
Produto 7,Livros,138.01,180,3.2
Produto 8,Alimentos,386.24,837,2.2
Produto 9,Eletrônicos,197.16,261,4.8
Produto 10,Alimentos,466.88,411,1.5
Produto 11,Livros,231.28,378,3.6
Produto 12,Eletrônicos,427.87,450,5.0
Produto 13,Livros,498.83,755,2.6
Produto 14,Roupas,321.96,30,3.3
Produto 15,Livros,423.87,570,3.7
Produto 16,Eletrônicos,205.30,234,3.0
Produto 17,Brinquedos,319.74,196,4.6
Produto 18,Livros,424.76,278,3.4
Produto 19,Roupas,231.49,482,4.7
Produto 20,Brinquedos,394.67,966,3.0
Produto 21,Livros,177.06,68,1.9
Produto 22,Alimentos,408.15,117,3.8
Produto 23,Roupas,463.06,858,4.0
Produto 24,Eletrônicos,204.36,373,2.5
Produto 25,Alimentos,319.00,212,3.2
Produto 26,Alimentos,118.40,732,3.0
Produto 27,Brinquedos,198.57,613,2.2
Produto 28,Brinquedos,406.58,374,2.8
Produto 29,Alimentos,139.35,363,3.9
Produto 30,Livros,273.09,638,3.0
Produto 31,Livros,459.32,137,2.9
Produto 32,Roupas,493.10,125,3.9
Produto 33,Alimentos,406.45,788,1.9
Produto 34,Alimentos,65.01,845,2.1
Produto 35,Eletrônicos,388.80,629,1.3
Produto 36,Roupas,485.42,826,3.3
Produto 37,Alimentos,78.90,366,2.1
Produto 38,Eletrônicos,246.31,793,4.8
Produto 39,Livros,142.97,145,3.7
Produto 40,Eletrônicos,271.57,265,3.4
Produto 41,Brinquedos,467.79,823,1.7
Produto 42,Alimentos,454.79,605,4.0
Produto 43,Livros,323.85,81,3.4
Produto 44,Brinquedos,311.85,793,2.3
Produto 45,Eletrônicos,370.17,270,1.1
Produto 46,Brinquedos,391.46,553,2.8
Produto 47,Roupas,30.58,98,3.3
Produto 48,Brinquedos,417.59,592,3.5
Produto 49,Alimentos,12.19,477,3.3
Produto 50,Roupas,450.12,699,1.5

In [ ]:
df_produtos_com_indice.loc["Produto 5"]
#se colocar indice numerico da erro

Categoria do produto    Alimentos
Preço do produto            355.2
Itens vendidos                681
Avaliação do produto          1.4
Name: Produto 5, dtype: object

In [ ]:
df_produtos_com_indice.loc["Produto 15":"Produto 20"]

,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
Nome do produto,,,,
Produto 15,Livros,423.87,570,3.7
Produto 16,Eletrônicos,205.30,234,3.0
Produto 17,Brinquedos,319.74,196,4.6
Produto 18,Livros,424.76,278,3.4
Produto 19,Roupas,231.49,482,4.7
Produto 20,Brinquedos,394.67,966,3.0

In [ ]:
df_produtos_com_indice.loc["Produto 45", "Itens vendidos"]

np.int64(270)

In [ ]:
df_produtos_com_indice.loc[["Produto 45", "Produto 47", "Produto 16"], ["Preço do produto", "Itens vendidos"]]
#filtro para buscar coluna e linha

                 Preço do produto  Itens vendidos
Nome do produto
Produto 45                 370.17             270
Produto 47                  30.58              98
Produto 16                 205.30             234

In [ ]:
eletronicos = df_produtos_com_indice[df_produtos_com_indice["Categoria do produto"] == "Eletrônicos"]
eletronicos

,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
Nome do produto,,,,
Produto 2,Eletrônicos,117.81,308,3.4
Produto 4,Eletrônicos,296.20,255,4.5
Produto 9,Eletrônicos,197.16,261,4.8
Produto 12,Eletrônicos,427.87,450,5.0
Produto 16,Eletrônicos,205.30,234,3.0
Produto 24,Eletrônicos,204.36,373,2.5
Produto 35,Eletrônicos,388.80,629,1.3
Produto 38,Eletrônicos,246.31,793,4.8
Produto 40,Eletrônicos,271.57,265,3.4
Produto 45,Eletrônicos,370.17,270,1.1

In [ ]:
#Alterando valores no DataFrame
brinquedos = df_produtos_com_indice[df_produtos_com_indice["Categoria do produto"] == "Brinquedos"]
df_produtos_com_indice.loc[brinquedos.index, "Categoria do produto"] = "Infanto-juvenil"

In [ ]:
df_produtos_com_indice['Categoria do produto'].unique()

array(['Infanto-juvenil', 'Eletrônicos', 'Alimentos', 'Roupas', 'Livros'],
      dtype=object)

## desafio

1.carregar um arquivo CSV específico que contém feedbacks de clientes.

2.usar um LLM para classificar o sentimento de cada feedback como positivo, negativo ou neutro.

3.adicionar uma nova coluna ao nosso DataFrame, contendo essa classificação de sentimento (positivo, negativo ou neutro) que obtivemos a partir do arquivo CSV.

In [ ]:
# etapa 1
import pandas as pd

df_reviews = pd.read_csv("/content/reviews.csv")

In [ ]:
print(df_reviews.columns)
  # serve para verificar o titulo de cada coluna

Index(['reviewerID', 'asin', 'reviewerName', 'reviewText', 'unixReviewTime',
       'reviewTime', 'day_diff', 'helpful_yes', 'total_vote'],
      dtype='object')

OBS = lembrar de criar variavel para verificar isoladamente qualquer coluna

In [ ]:
# etapa 2
from groq import Groq

client_groq = Groq()

def classificar_sentimento(feedback):
  # função criada para classificar o o feedback do reviewText
  completion = client_groq.chat.completions.create(
      model="openai/gpt-oss-20b",
      messages=[
      {
        "role": "user",
        "content":f'Classifique o sentimento do feedback abaixo.Responda apenas com: Positivo, Negativo, Neutro  Feedback:{feedback}'
      }
    ],
    temperature=1,
)

  return completion.choices[0].message.content.strip()

In [ ]:
df_reviews["sentimento"] = df_reviews["reviewText"].apply(classificar_sentimento)
  # serve para criar a coluna de sentimentos na tabela utilizando a função criada

In [ ]:
revisao = df_reviews[(df_reviews['sentimento'] == 'Positivo') & (df_reviews['reviewText'].str.contains('great'))]
revisao

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,sentimento
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positivo
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0,Positivo
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0,Positivo

In [ ]:
verificar_colunas = df_reviews['reviewText']
  # serve para verificar o conteudo da coluna especificada

In [ ]:
# etapa 2 alternativa
from groq import Groq

sentimentos = []

client_groq = Groq()

for review_numero, resenha in enumerate(verificar_colunas):
  completion = client_groq.chat.completions.create(
      model="openai/gpt-oss-20b",
      messages=[
      {
        "role": "user",
        "content":f'Classifique o sentimento do feedback abaixo.Responda apenas com: Positivo, Negativo, Neutro  Feedback:{resenha}'
      }
    ],
    temperature=1,
)
  resposta = completion.choices[0].message.content.strip()
    #opcional, fiz pra deixar organizado
  sentimentos.append(resposta)
  #print(f"Resenha {review_numero}: '{resenha}' -> Sentimento: {resposta}")

In [ ]:
# Etapa 3 alternativa
#df_reviews["Análises de Sentimentos"] = sentimentos
  # criação de colunas

In [ ]:
revisao = df_reviews[(df_reviews['sentimento'] == 'Positivo') & (df_reviews['reviewText'].str.contains('great'))]
revisao

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,sentimento
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positivo
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0,Positivo
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0,Positivo
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0,Positivo

## Para saber mais: set_index em pandas

In [ ]:
# Exemplo simples: convertendo uma coluna para índice
import pandas as pd

dados = {'Produto': ['Produto A', 'Produto B', 'Produto C'],
         'Preço': [100, 150, 200],
         'Estoque': [30, 20, 50]}
df = pd.DataFrame(dados)

# Transformando a coluna 'Produto' em índice
df_indexado = df.set_index('Produto')
print(df_indexado)
df

           Preço  Estoque
Produto
Produto A    100       30
Produto B    150       20
Produto C    200       50

     Produto  Preço  Estoque
0  Produto A    100       30
1  Produto B    150       20
2  Produto C    200       50

método reset_index, que reverte a operação e recria um índice numérico padrão.

Exercicio

Crie um DataFrame com 5 colunas: nome do produto, categoria, preço, avaliação e itens vendidos;

Utilize pd.read_csv para importar dados de um arquivo CSV;

Exiba o DataFrame completo e com .head para visualizar os registros iniciais;

Selecione uma coluna específica utilizando a notação de colchetes;

Extraia valores únicos de uma coluna com os métodos unique ou set;

Realize um filtro simples para selecionar registros com categoria igual a 'eletrônicos';

Aplique um filtro condicional para obter produtos com avaliação menor que 2.0;

Combine filtros usando o operador & para condições simultâneas, como categoria e preço;

Utilize o método iloc para selecionar linhas por índices numéricos;

Acesse registros com índices textuais utilizando o método loc após definir um novo índice;

Implemente o desafio: carregue o CSV de reviews, utilize um LLM para classificar o sentimento de cada feedback e adicione essa classificação como nova coluna no DataFrame.

In [ ]:
df_reviews ["sentimento"] = sentimentos

In [ ]:
df_reviews ["sentimento"] == 'Positivo'
df_review_positivo = df_reviews [df_reviews ["sentimento"] == 'Positivo']

In [ ]:
df_review_positivo.shape

(12, 10)

In [ ]:
elogios = df_review_positivo['reviewText']
elogios

1     This think has worked out great.Had a diff. br...
2     Bought it with Retail Packaging, arrived legit...
3     It's mini storage.  It doesn't do anything els...
4     I have it in my phone and it never skips a bea...
7     The memory card is an excellent condition and ...
12    everything about it was great, except for the ...
13    Used in my phone it's plenty fast and works ju...
16    good card. work as describes. haven't had any ...
17    I got this because I just couldn't pass up the...
29    Does what it says. Hasn't broken yet, and I ho...
32    I have two of these and use them for my Galazy...
Name: reviewText, dtype: object

Para usar o join, precisamos escolher um separador. Como é um texto, deve estar entre aspas. Podemos escolher, por exemplo, cinco hashtags como separador, pois é improvável que elas apareçam no texto.

In [ ]:
elogios_geral = '#####'.join(elogios)
elogios_geral

"This think has worked out great.Had a diff. bran 64gb card and if went south after 3 months.This one has held up pretty well since I had my S3, now on my Note3.*** update 3/21/14I've had this for a few months and have had ZERO issue's since it was transferred from my S3 to my Note3 and into a note2. This card is reliable and solid!Cheers!#####Bought it with Retail Packaging, arrived legit, in a orange envelope, english version not asian like the picture shows. arrived quickly, bought a 32 and 16 both retail packaging for my htc one sv and Lg Optimus, both cards in working order, probably best price you'll get for a nice sd card#####It's mini storage.  It doesn't do anything else and it's not supposed to.  I purchased it to add additional storage to my Microsoft Surface Pro tablet which only come in 64 and 128 GB.  It does what it's supposed to and SanDisk has a long standing reputation that speaks for itself.#####I have it in my phone and it never skips a beat. File transfers are speedy and have not had any corruption issues or memory fade issues as I would expect from the Sandisk brand. Great card to own. Why entrust your precious files to a slightly cheaper piece of crap? If you lose everything can you forgive yourself for not spending the extra couple bucks on a trusted product that goes through good QA?#####The memory card is an excellent condition and work as described. Dependable and easy to use. An excellent choice for the enthusiast who requires more storage.#####everything about it was great, except for the adapter.  It was to tight i had to use a tool to take it back out of the adapter causing me to chip it. so my fault i guess, but i also bought a 16gb version and the adapter for that one was fine.#####Used in my phone it's plenty fast and works just like it should. Unexpectedly comes with mini and full SD card size adapters, which is nice. &#34;Fool-proof&#34; packaging or whatever it was, that was laughable. Packaging was decent it just shouldn't have bragged about being impossible to mess up when I messed it up.#####good card. work as describes. haven't had any issue with it or going pass metal detectors. no lost files or missing files.#####I got this because I just couldn't pass up the deal, $17.99. It has been incredibly fast in my HTC Sensation 4g. Pictures are taken and saved instantaneously. Only had it a few days, but have been very happy. Shipping was fast and the packaging was easy to open which is always great in my book. Only issue I had was I had to format it on my computer first before my phone was able to recognize it.#####Does what it says. Hasn't broken yet, and I hope it doesn't break. I've had luck with this brand before. Usually get bored with the product before it breaks.#####I have two of these and use them for my Galazy Note 2. It's great having the flexibility to keep extra storage with you for your 'phablet'.So far they have done what they are intended to do."

In [ ]:
completion = client_groq.chat.completions.create(
      model="openai/gpt-oss-20b",
      messages=[
      {
        "role": "user",
        "content":f'''resuma todos os feedback em apenas uma palavra, mas eu quero que voce categorize cada um delas
                    lembrando que elas estão separadas por #####

                    exemplo: qualidade, custo-beneficio, ... quero saber os pontos fortes do que eu tive como feedback

                    Regras:
                    - Não explique.
                    - separe apenas em 5 categorias e separadas por virgula
                    - traduzido em portugues


                     Esses são os feedback  {elogios_geral}'''
      }
    ],
    temperature=1,
)
resposta = completion.choices[0].message.content.strip()
print(resposta)

confiabilidade, desempenho, preço, embalagem, compatibilidade

In [ ]:
ponto_forte = resposta.split(', ')
ponto_forte

['confiabilidade', 'desempenho', 'preço', 'embalagem', 'compatibilidade']

In [ ]:
desempenho = client_groq.chat.completions.create(
      model="openai/gpt-oss-20b",
      messages=[
      {
        "role": "user",
        "content":f'''Você é um analista de dados. Vou te passar muitas resenhas
        positivas de análises de um produto, separadas por '#####'', e eu quero que
        Retorne APENAS o texto JSON.
        essas 3 chaves:.

       - feedback_original - texto original
       - feedback_traduzido - texto traduzido em portugues
       - categoria - {ponto_forte}

        Exemplo:
        {{'resenha_original': 'I did like the color of the product',
        'resenha_pt': 'Eu gostei da cor do produto',
        'categoria': 'design'}}

        Esses são os feedback positivos {elogios_geral}'''
      }
    ],
      max_completion_tokens=6000
)

arquivo_json = desempenho.choices[0].message.content.strip()
print(arquivo_json)

[
  {
    "feedback_original": "These think has worked out great.Had a diff. bran 64gb card and if went south after 3 months.This one has held up pretty well since I had my S3, now on my Note3.*** update 3/21/14I've had this for a few months and have had ZERO issue's since it was transferred from my S3 to my Note3 and into a note2. This card is reliable and solid!Cheers!",
    "feedback_traduzido": "Este cartão funcionou muito bem. Tinha um cartão de 64GB de outra marca e ele falhou depois de 3 meses. Este cartão se manteve bem desde que eu tinha meu S3, agora no meu Note3. *** atualização 21/03/14. Tenho esse por alguns meses e não tive nenhum problema desde que foi transferido do meu S3 para o meu Note3 e para um Note2. Este cartão é confiável e sólido! Saudações!",
    "categoria": "confiabilidade"
  },
  {
    "feedback_original": "Bought it with Retail Packaging, arrived legit, in a orange envelope, english version not asian like the picture shows. arrived quickly, bought a 32 and 16 both retail packaging for my htc one sv and Lg Optimus, both cards in working order, probably best price you'll get for a nice sd card",
    "feedback_traduzido": "Comprado com embalagem varejista, chegou legítimo, em envelope laranja, versão inglesa não asiática como a foto mostra. Chegou rapidamente, comprei um 32 e 16 ambos com embalagem varejista para meu htc one sv e Lg Optimus, ambos cartões em funcionamento, provavelmente o melhor preço que você encontrará para um bom cartão SD",
    "categoria": "preço"
  },
  {
    "feedback_original": "It's mini storage.  It doesn't do anything else and it's not supposed to.  I purchased it to add additional storage to my Microsoft Surface Pro tablet which only come in 64 and 128 GB.  It does what it's supposed to and SanDisk has a long standing reputation that speaks for itself.",
    "feedback_traduzido": "É um armazenamento mini. Não faz nada além disso e não deveria. Comprado para adicionar armazenamento adicional ao meu tablet Microsoft Surface Pro que só vem em 64 e 128 GB. Faz o que deveria e a SanDisk tem uma longa reputação que fala por si mesma.",
    "categoria": "compatibilidade"
  },
  {
    "feedback_original": "I have it in my phone and it never skips a beat. File transfers are speedy and have not had any corruption issues or memory fade issues as I would expect from the Sandisk brand. Great card to own. Why entrust your precious files to a slightly cheaper piece of crap? If you lose everything can you forgive yourself for not spending the extra couple bucks on a trusted product that goes through good QA?",
    "feedback_traduzido": "Tenho ele no meu telefone e nunca perde o ritmo. Transferências de arquivos são rápidas e não tive problemas de corrupção ou perda de memória como eu esperaria da marca Sandisk. Ótimo cartão para possuir. Por que confiar seus arquivos preciosos a um produto ligeiramente mais barato? Se você perder tudo, pode se perdoar por não ter gasto uns trocados extras em um produto confiável que passa por boa QA?",
    "categoria": "confiabilidade"
  },
  {
    "feedback_original": "The memory card is an excellent condition and work as described. Dependable and easy to use. An excellent choice for the enthusiast who requires more storage.",
    "feedback_traduzido": "O cartão de memória está em excelente condição e funciona como descrito. Confiável e fácil de usar. Uma excelente escolha para o entusiasta que precisa de mais armazenamento.",
    "categoria": "confiabilidade"
  },
  {
    "feedback_original": "everything about it was great, except for the adapter.  It was to tight i had to use a tool to take it back out of the adapter causing me to chip it. so my fault i guess, but i also bought a 16gb version and the adapter for that one was fine.",
    "feedback_traduzido": "Tudo sobre ele foi ótimo, exceto o adaptador. Ele estava muito apertado, tive que usar uma ferramenta para tirá-lo do adaptador causando uma rachadura. então meu erro supongo, mas eu também comprei uma versão de 16gb e o adaptador para aquela foi bom.",
    "categoria": "compatibilidade"
  },
  {
    "feedback_original": "Used in my phone it's plenty fast and works just like it should. Unexpectedly comes with mini and full SD card size adapters, which is nice. “Fool-proof” packaging or whatever it was, that was laughable. Packaging was decent it just shouldn't have bragged about being impossible to mess up when I messed it up.",
    "feedback_traduzido": "Usado no meu telefone, é rápido e funciona como deveria. Chega inesperadamente com adaptadores de tamanho mini e full SD, o que é legal. \"Fool-proof\" embalagem ou algo, foi hilário. Embalagem foi decente, só não deveria ter falado que era impossível de bagunçar quando eu bagunçou.",
    "categoria": "embalagem"
  },
  {
    "feedback_original": "good card. work as describes. haven't had any issue with it or going pass metal detectors. no lost files or missing files.",
    "feedback_traduzido": "Bom cartão. Funciona como descreve. Não tive nenhum problema com ele nem passou nos detectores de metal. Nenhum arquivo perdido ou faltando.",
    "categoria": "confiabilidade"
  },
  {
    "feedback_original": "I got this because I just couldn't pass up the deal, $17.99. It has been incredibly fast in my HTC Sensation 4g. Pictures are taken and saved instantaneously. Only had it a few days, but have been very happy. Shipping was fast and the packaging was easy to open which is always great in my book. Only issue I had was I had to format it on my computer first before my phone was able to recognize it.",
    "feedback_traduzido": "Comprei porque não consegui resistir à oferta, $17,99. Foi incrivelmente rápido no meu HTC Sensation 4g. Fotos são tiradas e salvas instantaneamente. Só o tive alguns dias, mas fiquei muito feliz. O envio foi rápido e a embalagem fácil de abrir, sempre ótimo para mim. Único problema foi que precisei formatá-lo no meu computador antes que meu telefone o reconhecesse.",
    "categoria": "preço"
  },
  {
    "feedback_original": "Does what it says. Hasn't broken yet, and I hope it doesn't break. I've had luck with this brand before. Usually get bored with the product before it breaks.",
    "feedback_traduzido": "Faz o que diz. Ainda não quebrou, e espero que não quebre. Tive sorte com essa marca antes. Normalmente me canso do produto antes de quebrar.",
    "categoria": "confiabilidade"
  },
  {
    "feedback_original": "I have two of these and use them for my Galazy Note 2. It's great having the flexibility to keep extra storage with you for your 'phablet'.So far they have done what they are intended to do.",
    "feedback_traduzido": "Tenho dois desses e os uso no meu Galaxy Note 2. É ótimo ter flexibilidade para manter armazenamento extra com você para seu \"phablet\". Até agora eles fizeram o que deveriam.",
    "categoria": "compatibilidade"
  }
]

In [ ]:
import json

In [ ]:
#arquivo_json_atualizado = arquivo_json.replace("```json", "").replace("```", "")

dicionario_de_resenhas_positivas = json.loads(arquivo_json_atualizado)
dicionario_de_resenhas_positivas

[{'feedback_original': "These think has worked out great.Had a diff. bran 64gb card and if went south after 3 months.This one has held up pretty well since I had my S3, now on my Note3.*** update 3/21/14I've had this for a few months and have had ZERO issue's since it was transferred from my S3 to my Note3 and into a note2. This card is reliable and solid!Cheers!",
  'feedback_traduzido': 'Este cartão funcionou muito bem. Tinha um cartão de 64GB de outra marca e ele falhou depois de 3 meses. Este cartão se manteve bem desde que eu tinha meu S3, agora no meu Note3. *** atualização 21/03/14. Tenho esse por alguns meses e não tive nenhum problema desde que foi transferido do meu S3 para o meu Note3 e para um Note2. Este cartão é confiável e sólido! Saudações!',
  'categoria': 'confiabilidade'},
 {'feedback_original': "Bought it with Retail Packaging, arrived legit, in a orange envelope, english version not asian like the picture shows. arrived quickly, bought a 32 and 16 both retail packaging for my htc one sv and Lg Optimus, both cards in working order, probably best price you'll get for a nice sd card",
  'feedback_traduzido': 'Comprado com embalagem varejista, chegou legítimo, em envelope laranja, versão inglesa não asiática como a foto mostra. Chegou rapidamente, comprei um 32 e 16 ambos com embalagem varejista para meu htc one sv e Lg Optimus, ambos cartões em funcionamento, provavelmente o melhor preço que você encontrará para um bom cartão SD',
  'categoria': 'preço'},
 {'feedback_original': "It's mini storage.  It doesn't do anything else and it's not supposed to.  I purchased it to add additional storage to my Microsoft Surface Pro tablet which only come in 64 and 128 GB.  It does what it's supposed to and SanDisk has a long standing reputation that speaks for itself.",
  'feedback_traduzido': 'É um armazenamento mini. Não faz nada além disso e não deveria. Comprado para adicionar armazenamento adicional ao meu tablet Microsoft Surface Pro que só vem em 64 e 128 GB. Faz o que deveria e a SanDisk tem uma longa reputação que fala por si mesma.',
  'categoria': 'compatibilidade'},
 {'feedback_original': 'I have it in my phone and it never skips a beat. File transfers are speedy and have not had any corruption issues or memory fade issues as I would expect from the Sandisk brand. Great card to own. Why entrust your precious files to a slightly cheaper piece of crap? If you lose everything can you forgive yourself for not spending the extra couple bucks on a trusted product that goes through good QA?',
  'feedback_traduzido': 'Tenho ele no meu telefone e nunca perde o ritmo. Transferências de arquivos são rápidas e não tive problemas de corrupção ou perda de memória como eu esperaria da marca Sandisk. Ótimo cartão para possuir. Por que confiar seus arquivos preciosos a um produto ligeiramente mais barato? Se você perder tudo, pode se perdoar por não ter gasto uns trocados extras em um produto confiável que passa por boa QA?',
  'categoria': 'confiabilidade'},
 {'feedback_original': 'The memory card is an excellent condition and work as described. Dependable and easy to use. An excellent choice for the enthusiast who requires more storage.',
  'feedback_traduzido': 'O cartão de memória está em excelente condição e funciona como descrito. Confiável e fácil de usar. Uma excelente escolha para o entusiasta que precisa de mais armazenamento.',
  'categoria': 'confiabilidade'},
 {'feedback_original': 'everything about it was great, except for the adapter.  It was to tight i had to use a tool to take it back out of the adapter causing me to chip it. so my fault i guess, but i also bought a 16gb version and the adapter for that one was fine.',
  'feedback_traduzido': 'Tudo sobre ele foi ótimo, exceto o adaptador. Ele estava muito apertado, tive que usar uma ferramenta para tirá-lo do adaptador causando uma rachadura. então meu erro supongo, mas eu também comprei uma versão de 16gb e o adaptador para aquela foi bom.',
  'categoria': 'compatibilidade'},
 {'feedback_original': "Used in my phone it's plenty fast and works just like it should. Unexpectedly comes with mini and full SD card size adapters, which is nice. “Fool-proof” packaging or whatever it was, that was laughable. Packaging was decent it just shouldn't have bragged about being impossible to mess up when I messed it up.",
  'feedback_traduzido': 'Usado no meu telefone, é rápido e funciona como deveria. Chega inesperadamente com adaptadores de tamanho mini e full SD, o que é legal. "Fool-proof" embalagem ou algo, foi hilário. Embalagem foi decente, só não deveria ter falado que era impossível de bagunçar quando eu bagunçou.',
  'categoria': 'embalagem'},
 {'feedback_original': "good card. work as describes. haven't had any issue with it or going pass metal detectors. no lost files or missing files.",
  'feedback_traduzido': 'Bom cartão. Funciona como descreve. Não tive nenhum problema com ele nem passou nos detectores de metal. Nenhum arquivo perdido ou faltando.',
  'categoria': 'confiabilidade'},
 {'feedback_original': "I got this because I just couldn't pass up the deal, $17.99. It has been incredibly fast in my HTC Sensation 4g. Pictures are taken and saved instantaneously. Only had it a few days, but have been very happy. Shipping was fast and the packaging was easy to open which is always great in my book. Only issue I had was I had to format it on my computer first before my phone was able to recognize it.",
  'feedback_traduzido': 'Comprei porque não consegui resistir à oferta, $17,99. Foi incrivelmente rápido no meu HTC Sensation 4g. Fotos são tiradas e salvas instantaneamente. Só o tive alguns dias, mas fiquei muito feliz. O envio foi rápido e a embalagem fácil de abrir, sempre ótimo para mim. Único problema foi que precisei formatá-lo no meu computador antes que meu telefone o reconhecesse.',
  'categoria': 'preço'},
 {'feedback_original': "Does what it says. Hasn't broken yet, and I hope it doesn't break. I've had luck with this brand before. Usually get bored with the product before it breaks.",
  'feedback_traduzido': 'Faz o que diz. Ainda não quebrou, e espero que não quebre. Tive sorte com essa marca antes. Normalmente me canso do produto antes de quebrar.',
  'categoria': 'confiabilidade'},
 {'feedback_original': "I have two of these and use them for my Galazy Note 2. It's great having the flexibility to keep extra storage with you for your 'phablet'.So far they have done what they are intended to do.",
  'feedback_traduzido': 'Tenho dois desses e os uso no meu Galaxy Note 2. É ótimo ter flexibilidade para manter armazenamento extra com você para seu "phablet". Até agora eles fizeram o que deveriam.',
  'categoria': 'compatibilidade'}]

In [ ]:
len(dicionario_de_resenhas_positivas)

11

In [ ]:
dicionario_de_resenhas_positivas[10]

{'feedback_original': "I have two of these and use them for my Galazy Note 2. It's great having the flexibility to keep extra storage with you for your 'phablet'.So far they have done what they are intended to do.",
 'feedback_traduzido': 'Tenho dois desses e os uso no meu Galaxy Note 2. É ótimo ter flexibilidade para manter armazenamento extra com você para seu "phablet". Até agora eles fizeram o que deveriam.',
 'categoria': 'compatibilidade'}